import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'To do app',
  description: 'Generated by Ajmal Khan',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="bg-blue-200 flex items-center justify-center">Awsome To Do app</h1>
        {children}</body>
    </html>
  )
}
